docs:
	Rscript -e 'devtools::document()'

test:
	Rscript -e 'devtools::test()'

git:
	@git add --all
	@git --no-pager diff HEAD
	@echo "Please type commit message:";
	@read commit_message;\
	git commit -m "$$commit_message";

publish: docs test git
	Rscript -e 'devtools::build()'
	@git push origin master;
